#include "PluginProcessor.h"
#include "PluginEditor.h"
#include <cmath>
const char* VST3PlusVocalsSafeV2Processor::ids[paramCount]={"mcomp","msat","mair","mrev","mdel","mlevel","dw","dt","dr","dd","dl","aw","adist","ar","adel","al","input","mix","output"};
const char* VST3PlusVocalsSafeV2Processor::names[paramCount]={"Main Comp","Main Sat","Main Air","Main Reverb","Main Delay","Main Level","Double Width","Double Timing","Double Reverb","Double Delay","Double Level","Adlib Width","Adlib Dist","Adlib Reverb","Adlib Delay","Adlib Level","Input","Dry Wet","Output"};
float VST3PlusVocalsSafeV2Processor::mins[paramCount]={0,0,0,0,0,-24,0,5,0,0,-48,0,0,0,0,-48,-18,0,-18};
float VST3PlusVocalsSafeV2Processor::maxs[paramCount]={100,100,100,100,100,12,200,45,100,100,6,200,100,100,100,6,18,100,18};
float VST3PlusVocalsSafeV2Processor::defs[paramCount]={35,12,22,18,8,0,135,18,18,12,-14,155,22,30,28,-17,0,100,0};
VST3PlusVocalsSafeV2Processor::VST3PlusVocalsSafeV2Processor():AudioProcessor(BusesProperties().withInput("Input",juce::AudioChannelSet::stereo(),true).withOutput("Output",juce::AudioChannelSet::stereo(),true)){for(int i=0;i<paramCount;++i){auto*p=new juce::AudioParameterFloat(juce::ParameterID{ids[i],1},names[i],juce::NormalisableRange<float>{mins[i],maxs[i]},defs[i]);params[(size_t)i]=p;addParameter(p);}}
void VST3PlusVocalsSafeV2Processor::setParam(Param p,float v){auto*q=params[(size_t)p];q->setValueNotifyingHost(q->convertTo0to1(juce::jlimit(mins[p],maxs[p],v)));}
float VST3PlusVocalsSafeV2Processor::getParam(Param p)const{return params[(size_t)p]->get();}
bool VST3PlusVocalsSafeV2Processor::isBusesLayoutSupported(const BusesLayout&l)const{auto i=l.getMainInputChannelSet(),o=l.getMainOutputChannelSet();return i==o&&(i==juce::AudioChannelSet::mono()||i==juce::AudioChannelSet::stereo());}
void VST3PlusVocalsSafeV2Processor::prepareToPlay(double s,int){sr=s;int z=(int)(s*2)+8;mainL.assign(z,0);mainR.assign(z,0);dblL.assign(z,0);dblR.assign(z,0);adL.assign(z,0);adR.assign(z,0);mainPos=dblPos=adPos=0;revL=revR=0;}
static int rd(int w,int off,int z){int p=w-off;while(p<0)p+=z;return p%z;}
void VST3PlusVocalsSafeV2Processor::processBlock(juce::AudioBuffer<float>&b,juce::MidiBuffer&){juce::ScopedNoDenormals nd;int ch=b.getNumChannels(),n=b.getNumSamples();if(ch<1||n<1||mainL.empty())return;juce::AudioBuffer<float>dry;dry.makeCopyOf(b);float ig=juce::Decibels::decibelsToGain(getParam(inputGain)),comp=getParam(mainComp)/100.f,sat=getParam(mainSat)/100.f,air=getParam(mainAir)/100.f,rv=getParam(mainRev)/100.f,dm=getParam(mainDelay)/100.f,dlv=juce::Decibels::decibelsToGain(getParam(dblLevel)),dw=getParam(dblWidth)/200.f,alv=juce::Decibels::decibelsToGain(getParam(adLevel)),aw=getParam(adWidth)/200.f,dist=getParam(adDist)/100.f;int z=(int)mainL.size(),mo=(int)(sr*.235),dof=(int)(sr*(getParam(dblTime)/1000.f)),ao=(int)(sr*.315);static float pl=0,pr=0;for(int i=0;i<n;++i){float il=dry.getSample(0,i)*ig,ir=(ch>1?dry.getSample(1,i):il)*ig;auto fx=[&](float v,float&pv){float a=std::abs(v);if(a>.32f)v=std::copysign(.32f+(a-.32f)/(1+comp*6),v);v=std::tanh(v*(1+sat*3.5f))/(1+sat);float hi=v-pv;pv=v;return v+hi*air*.2f;};float L=fx(il,pl),R=fx(ir,pr);int m=rd(mainPos,mo,z);float mdL=mainL[m],mdR=mainR[m];mainL[mainPos]=L+mdL*.22f;mainR[mainPos]=R+mdR*.22f;L+=mdL*dm*.4f;R+=mdR*dm*.4f;revL=revL*.82f+L*.18f;revR=revR*.82f+R*.18f;L+=revL*rv*.38f;R+=revR*rv*.38f;int d=rd(dblPos,dof,z);float monoD=.5f*(dblL[d]+dblR[d]);dblL[dblPos]=il;dblR[dblPos]=ir;L+=monoD*dlv*(1+.2f*dw);R+=monoD*dlv*(1-.2f*dw);int a=rd(adPos,ao,z);float monoA=.5f*(adL[a]+adR[a]);adL[adPos]=std::tanh(il*(1+dist*4));adR[adPos]=std::tanh(ir*(1+dist*4));L+=monoA*alv*(1+.28f*aw);R+=monoA*alv*(1-.28f*aw);float wet=getParam(dryWet)/100.f;b.setSample(0,i,dry.getSample(0,i)*(1-wet)+L*wet);if(ch>1)b.setSample(1,i,dry.getSample(1,i)*(1-wet)+R*wet);if(++mainPos>=z)mainPos=0;if(++dblPos>=z)dblPos=0;if(++adPos>=z)adPos=0;}b.applyGain(juce::Decibels::decibelsToGain(getParam(mainLevel)+getParam(outputGain)));meter=b.getMagnitude(0,n);}
void VST3PlusVocalsSafeV2Processor::getStateInformation(juce::MemoryBlock&d){juce::MemoryOutputStream s(d,true);for(int i=0;i<paramCount;++i)s.writeFloat(params[i]->get());}
void VST3PlusVocalsSafeV2Processor::setStateInformation(const void*d,int bytes){juce::MemoryInputStream s(d,(size_t)bytes,false);for(int i=0;i<paramCount&&!s.isExhausted();++i)setParam((Param)i,s.readFloat());}
juce::AudioProcessorEditor*VST3PlusVocalsSafeV2Processor::createEditor(){return new VST3PlusVocalsSafeV2Editor(*this);}juce::AudioProcessor*JUCE_CALLTYPE createPluginFilter(){return new VST3PlusVocalsSafeV2Processor();}
